name: macOS Interactive Shell
on: 
  workflow_dispatch:
    inputs:
      os_version:
        description: '选择 macOS 版本'
        required: true
        default: 'macos-14'
        type: choice
        options:
          - macos-15
          - macos-14
          - macos-13

jobs:
  interactive-terminal:
    # 使用输入变量来决定系统版本
    runs-on: ${{ github.event.inputs.os_version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

